### ISSUE TITLE
义诊机构列表页

### ISSUE THREAD

**Issue by TechQuery** [wuhan2020/WebApp#10]
## 主要字段

1. 机构/个人名
2. 官网网址
3. 联系人（姓名、电话）
4. 每日接诊起止时刻
5. 备注

## 参考数据

https://shimo.im/sheets/JgXjYCJJTRQxJ3GP/MODOC/

**Comment by zhangyanbo2007** [comment]
现在网站瘫痪了吗？打不开啊https://wuhan2020.github.io/#

**Comment by gaohaoyue** [comment]
@TechQuery assign 给我吧

**Comment by songyanghe666** [comment]
@TechQuery 义诊列表页已经完成，请问一下怎么Git上来...，没账号啊

**Comment by TechQuery** [comment]
@michaelHe666 那你得先 Google 一下 GitHub 协作流程

**Comment by TechQuery** [comment]
@michaelHe666 接口好了，你再开个 pull request 吧

- 数据模型：https://github.com/wuhan2020/rest-api/blob/master/source/model/Clinic.ts
- 接口逻辑：https://github.com/wuhan2020/rest-api/blob/master/source/controller/Clinic.ts

**Comment by allenfantasy** [comment]
~~新的模块需求传送门：https://github.com/wuhan2020/wuhan2020/issues/289~~

更新：这个需求应该是提到 [新版网站](http://wuhan2020.org.cn/) （written by React）的…

**Comment by TechQuery** [comment]
39d3dd0
