### ISSUE TITLE
物流公司发布页

### ISSUE THREAD

**Issue by TechQuery** [wuhan2020/WebApp#12]
## 主要字段

1. 公司名
2. 官方网址
3. 服务城市
4. 运输方向（出/入）
5. 联系人（姓名、电话）
6. 是否承接个人业务
7. 备注

## 参考数据

https://shimo.im/sheets/RTHXp3ghtKXY3GcC/MODOC/

**Comment by gongzhibin** [comment]
@TechQuery assign 给我吧

**Comment by gongzhibin** [comment]
@TechQuery assign 给我吧
