### ISSUE TITLE
疫情趋势图(按城市划分)，可以分别看确诊、疑似、死亡、治愈的数量折线图

### ISSUE THREAD

**Issue by maobaolong** [wuhan2020/WebApp#13]

**Comment by TechQuery** [comment]
我觉得可以直接链接 https://3g.dxy.cn/newh5/view/pneumonia
或者你可以去 https://github.com/wuhan2020/map-viz 看看有啥要帮忙的

**Comment by sarahwang93** [comment]
I could join to help. Do you need support? I have background on web application

**Comment by lzfxp** [comment]
我在本地搭了个环境，但是因为做得比较晚，只有28、29、30三天的json数据，数据来源是腾讯新闻，目前网上的曲线图只有全国的，地市的数据有，但是没有图，另外，腾讯的数据中，只有各地市确认、死亡、治愈的数据，疑似的数据没有。如果有疑似的数据，可以做一些预测。

**Comment by bob798** [comment]
百度实时数据中有地市的数据，链接：https://voice.baidu.com/act/newpneumonia/newpneumonia#tab1。

**Comment by allenfantasy** [comment]
关于疫情趋势图的部分，已知 [丁香园](https://ncov.dxy.cn/ncovh5/view/pneumonia)，[腾讯](https://news.qq.com/zt2020/page/feiyan.htm)，[百度](https://voice.baidu.com/act/newpneumonia/newpneumonia) 都已经有了。快速的方法是在站点上引入一个超链接跳到以上的任意一个。

当然如果 https://github.com/wuhan2020/map-viz 那里有产出能 somehow 贴到站点上就最好了，但这个要看具体怎么操作。 @TechQuery 觉得呢？如果有需要的话我可以帮忙。

**Comment by allenfantasy** [comment]
刚才和 map team 的人碰了下，应该最快今晚能把组件准备好给网站 import。如果么有别人抢的话我来吧。 @TechQuery

**Comment by TechQuery** [comment]
@allenfantasy 这么多天没人提，估计没人和你抢，直接 PR，我随时准备合并

**Comment by sarahwang93** [comment]
这issue是我开的，有人写吗？没人我上了

**Comment by allenfantasy** [comment]
@sarahwang93 目前在等 [map-viz](https://github.com/wuhan2020/map-viz) 那边整理好可视化组件之后，再集成到网站上。

**Comment by allenfantasy** [comment]
或者先 [临时增加疑疫情地图的外部链接](https://github.com/wuhan2020/WebApp/issues/56)

**Comment by sarahwang93** [comment]
他们那边可视化组件用的啥？

**Comment by sarahwang93** [comment]
我研究一下 看能不能画个架构图出来。各位觉得同意吗？

**Comment by DoubleNou** [comment]
我是写后端的，这个需要数据过滤吗

**Comment by allenfantasy** [comment]
@sarahwang93 应该是基于 ECharts 的。由于目前这个项目用的是 [WebCell](https://web-cell.dev/) 所以他们应该还要封装一个 webCell 的组件。或者你先 [加 Slack 进来](https://join.slack.com/t/wuhan2020/shared_invite/enQtOTI2NTU1NzU3MTM2LWQ1YjIzMDllYjYzYTE1OTNhMWU4OTZkOGYzOGJhOWM2MzdlMjgwMmZiOWEzYTQwNmJkZDI4OWRmM2Q2ZDM1MTc)？这样就不用在 issue 里聊天 XD

@DoubleNou 需要。数据清洗和标准化的工作应该是在 https://github.com/wuhan2020/data-sync，也先加 Slack 讨论吧~

**Comment by sarahwang93** [comment]
艾玛 太好了。 哪个channel?拖我进去

**Comment by sarahwang93** [comment]
x需要。拖我进slack, 哪个讨论组？

**Comment by allenfantasy** [comment]
@sarahwang93 点刚才我给你那个链接先进来。频道传送门：https://github.com/wuhan2020/wuhan2020#slack%E9%A2%91%E9%81%93%E5%AF%BC%E8%88%AA 先找前端组进来。

**Comment by allenfantasy** [comment]
map team 的 webCell 版本的组件已经 ready：https://github.com/wuhan2020/map-viz/ 💯 

准备接入

**Comment by allenfantasy** [comment]
初步是能接入的。但要同时兼容 PC 和移动端，样式还要调一下。
目前没有设计稿支持，但 map team 的人交互已经做的很好了（也用心调了配色），所以会直接搬运。

预计最迟明晚可以发一个 PR

**Comment by allenfantasy** [comment]
latest branch: https://github.com/allenfantasy/WebApp/tree/issue13-virusMap

**Comment by maobaolong** [comment]
这个issue强调的是，每个城市或者区的疫情趋势图。不是全国的趋势图

**Comment by allenfantasy** [comment]
@maobaolong 那这个的难点就主要是在数据上了。

btw, try do sth if u could help
