### ISSUE TITLE
医院急需物资页面报错，无法加载数据

### ISSUE THREAD

**Issue by zhang570751696** [wuhan2020/WebApp#16]
报下列错误：
1. GET https://vuqjf9paihid.leanapp.cn/session 401 ()
2. HTTPRequest.ts:64 Uncaught TypeError: e.trim(...).matchAll is not a function
    at p (HTTPRequest.ts:64)
    at XMLHttpRequest.d.onload (HTTPRequest.ts:98)

**Comment by TechQuery** [comment]
1. GET `/session` 401 是正常的，这是在检查登录状态
2. 第二个有详细截图、描述吗？

**Comment by holidaying** [comment]
http://127.0.0.1:1234/#hospital，用ip地址访问么问题

**Comment by TechQuery** [comment]
没遇到过这种问题，发一下操作系统、命令行终端、Node.js 版本等信息看看

**Comment by zhang570751696** [comment]
在正式环境的页面上，目前已经可以打开了
