### ISSUE TITLE
医院界面API调用次数超限

### ISSUE THREAD

**Issue by yylou15** [wuhan2020/WebApp#19]
网站aapi server托管在第三方云平台，好像对开发版的调用次数有限制，coder看下能否买一点调用量或者走自有服务器，如果需要我这可以做代理
<img width="1680" alt="QQ20200128-233748@2x" src="https://user-images.githubusercontent.com/32712286/73278871-3515cb80-4227-11ea-9bd1-e4595cc71557.png">

**Comment by TechQuery** [comment]
因为本 Web 应用还没专门做宣传，没想到大家开发、使用有这么大的热情，刚把开发、生产容器拆开
https://github.com/wuhan2020/rest-api#%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE

**Comment by TechQuery** [comment]
已通过捐助解决 https://github.com/wuhan2020/rest-api#%E7%89%B9%E5%88%AB%E6%84%9F%E8%B0%A2
