### ISSUE TITLE
有关此前端项目的一点建议

### ISSUE THREAD

**Issue by shadowings-zy** [wuhan2020/WebApp#2]
您好，我是一名前端开发者，是从主库的issue过来的。
我这边想提供每日疫情数据，接入到本前端项目中。
本来这部分数据展示的代码我已经使用react+echart+antdesign写好了，但我读过项目的源代码后感觉技术栈有些小众，完全无法直接接入。

所以现在想探讨一下，是应该我直接将本部分数据提供给您，由您来负责接入？还是说我们合作使用一些比较常见的前端框架和组件库（比如react，vue，antdesign，element-ui等）重构一下代码？

我读了一遍代码后觉得如果使用react这类应用比较广的前端框架，配合antdesign之类的组件库中的Card，Table等组件能够轻松快速地构建出更友好的页面（重构的工作量不会超过8小时），并且能够更方便地让更多的开发者参与进来。

**Comment by TechQuery** [comment]
1. 本 organization 的后端项目在负责数据接口，后面会提供统一的数据提交方式

2. WebCell 就是我对其它过重技术栈的不爽才开发的，但又都是基于成熟的底层技术（Web Components、TypeScript、BootStrap、Parcel 等），本项目就是以比同组织另一个 Ant Design 前端项目更快的开发速度脱颖而出的（年前一个只会 PHP、Vue 的妹子一天就上手当主力了）

**Comment by shadowings-zy** [comment]
哦哦了解了~

**Comment by dhcn** [comment]
*.github.io域名是一定程度被墙的。
疫情面前需要发挥群众的力量，小众不利于协作, 今朝今时不是谈某个IT技术之优劣。

**Comment by TechQuery** [comment]
1. `*.github.io` 会被微信等 App 多加一层“安全提示”页，但从未被“墙”，我们正在找不被“提示”的域名

2. 此危机攸关之时，当然不是争辩技术优劣的时候，所以基于**抄起键盘就是一把梭**的 WebCell，我迅速地开发出了线上可用的版本 https://wuhan2020.github.io/ ，累计 **16 小时**（包括 CSV 改 YAML、静态数据改半动态、半动态改 REST API 等 3 次大重构，还包括[后端接口][1]开发，而第一次重构时本 org 下基于 Ant Design 的项目只起了脚手架）

【历史记录】
- [fork 时的提交](https://github.com/EasyWebApp/wuhan2020/commits?author=TechQuery)
- [重新建库后的提交](https://github.com/wuhan2020/wuhan2020.github.io/commits?author=TechQuery)

---

- 任何大众的开源项目都是从小众开始的，不去应用永远小众
- 小众不代表*开发效率低*，**易学易用**的设计会比流行的*全家桶*更好上手
- 准正式版的 **Web Component**、大行其道的 **TypeScript**、零配置的 **Parcel**、简洁强大的 **BootStrap**，这些 WebCell 的基础设施都不是“小众”的东西，相信对热爱开源的大家不是什么困难

[1]: https://github.com/wuhan2020/rest-api

**Comment by TechQuery** [comment]
@shadowings-zy 可以去 https://wuhan2020.github.io/ 提交数据了

**Comment by daituzhang** [comment]
> 1. `*.github.io` 会被微信等 App 多加一层“安全提示”页，但从未被“墙”，我们正在找不被“提示”的域名
> 2. 此危机攸关之时，当然不是争辩技术优劣的时候，所以基于**抄起键盘就是一把梭**的 WebCell，我迅速地开发出了线上可用的版本 https://wuhan2020.github.io/ ，累计 **16 小时**（包括 CSV 改 YAML、静态数据改半动态、半动态改 REST API 等 3 次大重构，还包括[后端接口](https://github.com/wuhan2020/rest-api)开发，而第一次重构时本 org 下基于 Ant Design 的项目只起了脚手架）
> 
> 【历史记录】
> 
> * [fork 时的提交](https://github.com/EasyWebApp/wuhan2020/commits?author=TechQuery)
> * [重新建库后的提交](https://github.com/wuhan2020/wuhan2020.github.io/commits?author=TechQuery)
> 
> * 任何大众的开源项目都是从小众开始的，不去应用永远小众
> * 小众不代表_开发效率低_，**易学易用**的设计会比流行的_全家桶_更好上手
> * 准正式版的 **Web Component**、大行其道的 **TypeScript**、零配置的 **Parcel**、简洁强大的 **BootStrap**，这些 WebCell 的基础设施都不是“小众”的东西，相信对热爱开源的大家不是什么困难

@TechQuery 所以所有csv都会改成yaml吗？还是未改为yaml的数据直接parse csv？

**Comment by TechQuery** [comment]
@daituzhang 主库现在有程序同步更新 JSON，我们从 https://github.com/wuhan2020/wuhan2020/tree/master/data/json 取

**Comment by daituzhang** [comment]
@TechQuery 谢谢！除了医院和物流外的json，其他资源有人在更新吗？

**Comment by TechQuery** [comment]
@daituzhang 其他人在搞
https://github.com/wuhan2020/api-server
https://github.com/wuhan2020/data-sync

**Comment by huahua726** [comment]
一点浅见，用前端成熟的框架，参与进来的人会更多，比你一个人开发效率更快。就现在你上线的那个界面，我用react+python（接口）不要8小时。包括服务器部署，顶级域名上线。
在这种时候，不要炫耀技术，选择最大众的技术就是最好的选择。

**Comment by TechQuery** [comment]
@dhcn 已切换到国内备案域名 https://wuhan2020.kaiyuanshe.cn/

**Comment by Akagilnc** [comment]
> 1. 本 organization 的后端项目在负责数据接口，后面会提供统一的数据提交方式
> 2. WebCell 就是我对其它过重技术栈的不爽才开发的，但又都是基于成熟的底层技术（Web Components、TypeScript、BootStrap、Parcel 等），本项目就是以比同组织另一个 Ant Design 前端项目更快的开发速度脱颖而出的（年前一个只会 PHP、Vue 的妹子一天就上手当主力了）

拿事实说话好评。毕竟与其嘴上说。不如把东西实现出来看效率更有说服力

**Comment by lovepoem** [comment]
> 1. 本 organization 的后端项目在负责数据接口，后面会提供统一的数据提交方式
> 2. WebCell 就是我对其它过重技术栈的不爽才开发的，但又都是基于成熟的底层技术（Web Components、TypeScript、BootStrap、Parcel 等），本项目就是以比同组织另一个 Ant Design 前端项目更快的开发速度脱颖而出的（年前一个只会 PHP、Vue 的妹子一天就上手当主力了）

建议用通用的技术，大家能快速上手，减少学习的时间。

**Comment by TechQuery** [comment]
@lovepoem 若你长期关注本项目的 GitHub 和 Slack 的话，你会知道最大的瓶颈是[主库的数据结构][1]一直达不到**产品级要求**，无奈我只能开发[独立后端][2]，而**真正参与前端开发的小伙伴们上手都很快**，[开发进度][3]一直被后端接口卡着……

我一直坚信 Linux 作者 Linus Torvalds 的名言 ——
> Talk is cheap, show me the code!

[1]: https://github.com/wuhan2020/wuhan2020/tree/master/data/json
[2]: https://github.com/wuhan2020/rest-api
[3]: https://github.com/orgs/wuhan2020/projects/1?fullscreen=true

**Comment by BranceLee** [comment]
帮大佬做了一个二维码。
方便在朋友圈之间识别二维码传播信息和地址，希望有所帮助。
项目里底部发一个分享二维码或者网址的功能可能更方便传播吧，个人建议。

![武汉2020](https://user-images.githubusercontent.com/37168881/73603559-1d3f9e00-45bf-11ea-80f8-70e372ed5fcb.png)

![Wuhan2020](https://user-images.githubusercontent.com/37168881/73603547-d5207b80-45be-11ea-9e35-8044c197929e.png)

想用 React 帮帮忙的，先看看代码。
作者辛苦了！
