### ISSUE TITLE
待开发页面提示

### ISSUE THREAD

**Issue by WelshThomas** [wuhan2020/WebApp#20]
抱歉，我正在使用Google翻译，因为我只会说英语。
我确定这是有意的，但如果不是这样，则只能使用主页，物流页面和医院页面。
除此之外，在帮助人们和提供信息方面做得很好

**Comment by YagiGo** [comment]
Hi there, I can speak English. The translation here is not very clear and I have difficulties understanding your points here. So please share your opinion again in English so I can understand better. :)

**Comment by WelshThomas** [comment]
> Hi there, I can speak English. The translation here is not very clear and I have difficulties understanding your points here. So please share your opinion again in English so I can understand better. :)

So, on the website the only pages that **used** to work were; home, logistics and hospitals although now other pages work.
I was not sure if it was a bug or it was still a work in progress.

**Comment by TechQuery** [comment]
@lonewolfdesign WIP

**Comment by Rain1122** [comment]
> > Hi there, I can speak English. The translation here is not very clear and I have difficulties understanding your points here. So please share your opinion again in English so I can understand better. :)
> 
> So, on the website the only pages that **used** to work were; home, logistics and hospitals although now other pages work.
> I was not sure if it was a bug or it was still a work in progress.

I think this project is still in progress now.

**Comment by YagiGo** [comment]
> > Hi there, I can speak English. The translation here is not very clear and I have difficulties understanding your points here. So please share your opinion again in English so I can understand better. :)
> 
> So, on the website the only pages that **used** to work were; home, logistics and hospitals although now other pages work.
> I was not sure if it was a bug or it was still a work in progress.

These pages are still under development. Fixes have been made so that if you click these links, it will say that it is under development instead of doing nothing.

**Comment by TechQuery** [comment]
same as #24 & fixed in #29
