### ISSUE TITLE
微信分享网站链接https://wuhan2020.github.io/ 无法打开

### ISSUE THREAD

**Issue by bboychencan** [wuhan2020/WebApp#21]

**Comment by JGX020** [comment]
http://111.231.221.129
这有个备用的

**Comment by TechQuery** [comment]
@bboychencan @JGX020 能截图吗？

据我所知，微信对不常用顶级域会多加一个“安全提示”的先导页，但点“继续访问”即可进入，并不会完全不能用

**Comment by TechQuery** [comment]
已切换到国内备案域名 https://wuhan2020.kaiyuanshe.cn/
