### ISSUE TITLE
全国各省市石墨文档添加

### ISSUE THREAD

**Issue by xibolun** [wuhan2020/WebApp#28]
目前只有湖北省的各市医院的需求石墨文档，添加一个全国的？

**Comment by TechQuery** [comment]
我们的 PWA 一直支持全国的数据录入 https://wuhan2020.github.io/#hospital/edit

![image](https://user-images.githubusercontent.com/19969570/73344485-680a9e80-42bd-11ea-8d8d-b57c67022ee7.png)

**Comment by xibolun** [comment]
已进入，此issues关闭
