### ISSUE TITLE
【bug】义诊页面展示数据错误

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/WebApp#40]
**页面url** ： https://wuhan2020.kaiyuanshe.cn/#clinic
**问题 ：**     义诊页面展示数据错误，似乎展示的是物流信息

![image](https://user-images.githubusercontent.com/827112/73469722-cc168b00-43c1-11ea-84f7-91f6e2f87e77.png)

**Comment by TechQuery** [comment]
39d3dd0
