### ISSUE TITLE
[Bug]反复切换menu项目时，页面数据加载失败

### ISSUE THREAD

**Issue by jalog** [wuhan2020/WebApp#58]
例如：在“物流”、“酒店”两个菜单项来回切换时，页面数据一直显示正在加载，加载失败。

**Comment by TechQuery** [comment]
看一下控制台的代码、网络报错

**Comment by jalog** [comment]
暂时没发现错误原因 感觉很奇怪

**Comment by jalog** [comment]
暂时没发现错误原因，刷新浏览器页面时可以加载数据，但是反复切换菜单项时加载失败

**Comment by jalog** [comment]
反复切换菜单项时，页面显示Loading图标，将页面拖动到底端，数据才展示出来。

**Comment by jalog** [comment]
render(_, { loading, noMore }: HotelPageState) 
刷新页面时调用情况：
```
{loading: true, noMore: false} index.tsx:112 
{loading: true, noMore: false} index.tsx:112 
{loading: true, noMore: false} index.tsx:112 
{loading: true, noMore: false} index.tsx:112
{loading: false, noMore: false} index.tsx:112
```

切换到其他菜单项再切换回酒店菜单时的调用情况：
```
{loading: true, noMore: false} index.tsx:112 
{loading: true, noMore: false} index.tsx:112 
```

**Comment by jalog** [comment]
已修复，应修改state的初始值如下：
`state = { loading: false, noMore: false };`

**Comment by TechQuery** [comment]
> 已修复，应修改state的初始值如下：
> `state = { loading: false, noMore: false };`

忘了谁改了初试状态
