### ISSUE TITLE
信息组医院表  增加字段 有无问题

### ISSUE THREAD

**Issue by aefgijn** [wuhan2020/WebApp#61]
信息组医院表  增加捐赠字段 有无问题，若有需要注意什么？

**Comment by TechQuery** [comment]
“医院加捐赠”到底是个什么？能否详细描述？

**Comment by aefgijn** [comment]
> “医院加捐赠”到底是个什么？能否详细描述？

部分医院除了需要物资，还附加有捐赠信息（开户账号），但捐赠信息的录入又是另一张表，  这样的话就得二次录入了  工作量大

**Comment by TechQuery** [comment]
国家允许医院直接**接受捐款**了？

**Comment by aefgijn** [comment]
> 国家允许医院直接**接受捐款**了？

部分医院募捐信息里有

**Comment by TechQuery** [comment]
我想了下，两边都存**捐款信息**就得两边都写相应的处理逻辑，后期汇总处理更麻烦，需要捐款的还是单独去捐款页面录入
