### ISSUE TITLE
[Bug]导航右键打开链接时路由错误

### ISSUE THREAD

**Issue by rquanx** [wuhan2020/WebApp#62]
![image](https://user-images.githubusercontent.com/36622981/73609352-b72b3900-4607-11ea-9b1a-85fcb386eb67.png)

**Comment by TechQuery** [comment]
https://web-cell.dev/cell-router/ 沿用了 `<a href="" />`，再在 `new History()` 时确定**路由模式**，所以目前不能兼容这种操作
