### ISSUE TITLE
并不是所有前端都要在本地启动server，readme说明文件是否可加上此说明

### ISSUE THREAD

**Issue by Marla62** [wuhan2020/WebApp#64]
![image](https://user-images.githubusercontent.com/34474822/73610345-117cc780-4611-11ea-8be6-95c9d62acc60.png)
如图：是否可以直接加上此文字说明。
Mac在启动后端服务时，会报错无法启动。看了后台服务的issues，对应的工单已经被关闭。
https://github.com/wuhan2020/rest-api/issues/1

**Comment by allenfantasy** [comment]
确实是这样。 @Marla62 方便帮忙随手给个 PR 么？（我手头有另一个 issue 在爬 XD）

**UPDATE**：已建 PR
