### ISSUE TITLE
这个有没有推广，运行起来呀

### ISSUE THREAD

**Issue by luxiaoli2002** [wuhan2020/WebApp#68]

**Comment by luxiaoli2002** [comment]
有没有项目沟通平台

**Comment by bifenglin** [comment]
目前应该是在 https://app.slack.com/client/TT5U1VCPQ/CT93L48H5 上交流沟通，也可以通过 issue 进行沟通

**Comment by TechQuery** [comment]
@bifenglin 你可提个 PR 在 ReadMe 上加个 badge

**Comment by bifenglin** [comment]
@TechQuery 已提交。
