### ISSUE TITLE
爱心捐赠页面报401权限异常

### ISSUE THREAD

**Issue by bifenglin** [wuhan2020/WebApp#69]
## 页面地址
https://wuhan2020.kaiyuanshe.cn/#donation
## 页面展示
![image](https://user-images.githubusercontent.com/15813364/73634371-09b63500-469c-11ea-935a-def4ae8357a1.png)
## 报错信息
![image](https://user-images.githubusercontent.com/15813364/73634422-20f52280-469c-11ea-904f-0ad87dbb0d68.png)
## 猜测原因
server端获取数据权限不足
## 改进方法
需要与server 端协调。

**Comment by TechQuery** [comment]
这只是**应用首次启动**时尝试**拉取当前用户信息**，HTTP `401` 就是在表示“尚未登录”，是符合 **RESTful API** 的设计，并不是 bug
