### ISSUE TITLE
酒店列表页

### ISSUE THREAD

**Issue by TechQuery** [wuhan2020/WebApp#7]
## 主要字段

1. 店名
2. 地址（包括独立的省市区字段）
3. 官方网址
4. 可接待人数
5. 联系人

## 参考数据

https://shimo.im/sheets/Hd9C3QytrJK3RWxG/z1rye/

**Comment by osbornwang** [comment]
@TechQuery

**Comment by oDen7** [comment]
你好 请问这个页面 的  @TechQuery 
![31580209228_ pic_hd](https://user-images.githubusercontent.com/40536961/73258400-924a5680-4200-11ea-8d8a-34c5ed6f779f.jpg)
![21580209212_ pic_hd](https://user-images.githubusercontent.com/40536961/73258407-95454700-4200-11ea-9a16-57582b29ff3a.jpg)

**Comment by oDen7** [comment]
您好 请问 这个 页面 的 接口 在呢？
![31580209228_ pic_hd](https://user-images.githubusercontent.com/40536961/73258592-fff68280-4200-11ea-8f53-d0c26f784db9.jpg)

**Comment by oDen7** [comment]
@TechQuery  您好 我是一个前端开发者 ，请问这个页面 的 接口 在哪里？
链接: https://pan.baidu.com/s/1PXPgwmh4Clw884npZtJodA 提取码: dc69
QQ：1052277244

**Comment by TechQuery** [comment]
@oDen7 先做静态页面，数据我来接

**Comment by osbornwang** [comment]
> @oDen7 先做静态页面，数据我来接

emmm 页面我已经搞好了。。。。在等接口 编辑的页面也好了 也在等接口

**Comment by oDen7** [comment]
@TechQuery 建议是否 可以 撰写一篇  开源接口文档，这样效率会很高，对于前端来说，这些页面就是标准的curd，页面渲染，所以接口数据很重要。

**Comment by oDen7** [comment]
@TechQuery 严格意义上说，如果没有规范的ui设计图，完全可以按照 医院列表  页面的形式渲染数据，这样的话，只需要写出一个通用组件就可以。

**Comment by TechQuery** [comment]
> @TechQuery 建议是否 可以 撰写一篇 开源接口文档，这样效率会很高，对于前端来说，这些页面就是标准的curd，页面渲染，所以接口数据很重要。

后端接口本不应我们前端管，而是 https://github.com/wuhan2020/api-server 开发者的职责
