### ISSUE TITLE
[bug]: “医院急需物资“：省，市，区的联动有问题：选完“市”后再选择别的“省” #PwC

### ISSUE THREAD

**Issue by zhengewei** [wuhan2020/WebApp#79]
重现步骤：
1. 选择“湖北省”，“武汉市”
2. 直接选择人以别的省份，比如“河南省”

结果：
页面显示加载更多...

API参数：
province: 河南省
city: 武汉市

<img width="1009" alt="Screen Shot 2020-02-01 at 10 26 55 PM" src="https://user-images.githubusercontent.com/25046707/73593765-9056ff00-4542-11ea-8d88-e906f091aef0.png">

**Comment by TechQuery** [comment]
7311572
