### ISSUE TITLE
生产厂家列表页

### ISSUE THREAD

**Issue by TechQuery** [wuhan2020/WebApp#8]
## 主要字段

1. 厂名
2. 厂址（含独立省市区字段）
3. 资质证号
4. 官方网址
5. 联系人（姓名、电话）
6. 可生产物资
7. 备注

## 参考数据

https://shimo.im/sheets/pchvJ6ddyRHHdXtv/MODOC/

**Comment by songyanghe666** [comment]
联系人的名字和电话怎么放一起，接口写成一个吗？
这个连第一范式都不符合呀。
鉴于当前提供的字段我只能联系人信息格式为：“张三（1666666666）“这样的字符串OK吗？
@TechQuery

**Comment by TechQuery** [comment]
@michaelHe666 @daituzhang https://github.com/wuhan2020/rest-api/issues/3#issuecomment-580135655
