### ISSUE TITLE
DeepScan medium issue

### ISSUE THREAD

**Issue by chenrui333** [wuhan2020/WebApp#85]
link, https://deepscan.io/dashboard/#view=project&tid=7382&pid=9492&bid=123836&subview=issues

![image](https://user-images.githubusercontent.com/1580956/74093537-16be9400-4aa1-11ea-8878-13d74c88c682.png)

**Comment by TechQuery** [comment]
ESLint 对 TypeScript 在非 React 项目中的 JSX 语法检查有问题，我还要研究一下

**Comment by TechQuery** [comment]
因本项目由 WebCell v2 升到 v3，之前的问题全部消失，仅剩 DeepScan 自身对 **ECMAScript 装饰器**最新语法的不支持问题（已反馈给官方）：
https://deepscan.io/dashboard/#view=project&tid=24590&pid=27709&bid=889817&prid=&subview=issues
