### ISSUE TITLE
省市区的选择展示

### ISSUE THREAD

**Issue by xrkffgg** [wuhan2020/WebApp#87]
## 当前问题
当使用移动端时，由于尺寸较小，当选择字数多的省市区时，会超出屏幕宽度。

如选择：
内蒙古自治区 =》 呼和浩特市 =》 玉泉区

## 期待的正确输出

选项内容在当前屏幕尺寸中

**Comment by xrkffgg** [comment]
- 是否可将反显内容不放在按钮中？

**Comment by TechQuery** [comment]
“反显”是啥？

**Comment by xrkffgg** [comment]
就是选择的内容

**Comment by xrkffgg** [comment]
<img width="836" alt="WeChat097fde464002a3baa6889e3c418b6908" src="https://user-images.githubusercontent.com/29775873/74313029-dbc4a500-4dad-11ea-8107-ce2e09a33755.png">

按钮上显示 省市区，超出了默认宽度
