### ISSUE TITLE
捐助接受方列表页

### ISSUE THREAD

**Issue by TechQuery** [wuhan2020/WebApp#9]
## 主要字段

1. 机构名
2. 官方网址
3. 银行账户（开户行、账号、户名）
4. 联系人（姓名、电话）
5. 备注

## 参考数据

https://shimo.im/sheets/W3gxW6cwkYTDY6DD/

**Comment by holidaying** [comment]
我来认领

**Comment by TechQuery** [comment]
@holidaying @michaelHe666 你们到底谁做？

**Comment by holidaying** [comment]
基本页面和model接口写好了。merge进来就能用。其余的@michaelHe666来做

**Comment by TechQuery** [comment]
@holidaying 接口由 @michaelHe666 来接到页面上？

**Comment by holidaying** [comment]
一直merge不进来？

**Comment by holidaying** [comment]
![image](https://user-images.githubusercontent.com/12896717/73583422-0de02800-44cd-11ea-91f6-39cbed6ce66d.png)
